[tools]
bun = "latest"
npm = "latest"
"npm:saddle-cli" = "latest"

ripgrep = "latest"
"github:peteretelej/tree" = { version = "latest", rename_exe = "tree-cli" }

[settings.npm]
package_manager = "bun"

[tasks.default]
run = "mise tasks"

[tasks.upgrade-tools]
description = "Upgrade all development tools to their latest versions"
run = ["mise install", "mise up", "mise prune"]

[tasks.env-sync]
description = "Sync the virtual environment with pyproject.toml dependencies"
run = "uv sync -U --dev --all-extras --all-groups"

[tasks.format]
description = "Format source code and markdown files"
run = [
    "uv run undersort .",
    "uv run ruff check --select I --fix", # isort-equivalent sorting of imports
    "uv run ruff format .",
    "uv run mdformat .",
]


[tasks.add-skills]
description = "Add skills to the agent"
run = [
    "cls",
    "bun x skills add https://github.com/nicobailon/visual-explainer -a universal -y",
    "bun x skills add https://github.com/alinaqi/claude-bootstrap -s code-deduplication -a universal -y",
    "bun x skills add https://github.com/hardikpandya/stop-slop -a universal -y",
    "bun x skills add kreuzberg-dev/kreuzberg -a universal -y",
    "bun x skills add AlmogBaku/debug-skill -a universal -y",
]
