[tools]
bun = "latest"
npm = "latest"
"npm:saddle-cli" = "latest"

[settings.npm]
package_manager = "bun"

[tasks.default]
run = "mise tasks"


[tasks.add-skills]
description = "Add skills to the agent"
run = [
    "cls",
    "bun x skills add https://github.com/nicobailon/visual-explainer -a universal -y",
    "bun x skills add https://github.com/alinaqi/claude-bootstrap -s code-deduplication -a universal -y",
    "bun x skills add https://github.com/hardikpandya/stop-slop -a universal -y",
    "bun x skills add kreuzberg-dev/kreuzberg -a universal -y",
    "bun x skills add AlmogBaku/debug-skill -a universal -y",
]
