[tools]
bun = "latest"
npm = "latest"
"npm:saddle-cli" = "latest"

ripgrep = "latest"
"github:peteretelej/tree" = { version = "latest", rename_exe = "tree-cli" }

# Linter/formatter/type checker tools
"ruff" = "latest"
"ty" = "latest"
"pipx:mdformat" = {version = "latest", uvx = "true", uvx_args = "--with mdformat-front-matters"}
"pipx:undersort" = "latest"

[settings.npm]
package_manager = "bun"

[tasks.default]
run = "mise tasks"

[tasks.upgrade-tools]
description = "Upgrade all development tools to their latest versions"
run = ["mise install", "mise up", "mise prune"]

[tasks.env-sync]
description = "Sync the virtual environment with pyproject.toml dependencies"
run = "uv sync -U --dev --all-extras --all-groups"

[tasks.format]
description = "Format source code and markdown files"
run = [
    "undersort .",
    "ruff check --select I --fix", # isort-equivalent sorting of imports
    "ruff format .",
]

[tasks.format-md]
description = "Format Markdown files"
run = "uv tool run --with mdformat-front-matters mdformat . --exclude .config/ --end-of-line keep --number"

[tasks.add-skills]
description = "Add skills to the agent"
run = [
    "cls",
    # coding & tools skills
    "bun x skills add jr2804/prompts -a universal -y -s python-ultimate -s docx -s docx-svg -s docling-document-intelligence -s pdf -s pptx -s xlsx",
    # "bun x skills add AlmogBaku/debug-skill -a universal -y",

    "bun x skills add https://github.com/nicobailon/visual-explainer -a universal -y",
    "bun x skills add https://github.com/hardikpandya/stop-slop -a universal -y",

    # document intelligence skills
    "bun x skills add kreuzberg-dev/kreuzberg -a universal -y",
    "bun x skills add run-llama/llamaparse-agent-skills --skill liteparse -a universal -y",

]
